name: Build Vuepress and Sync Gitee
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm i

    # Vuepress Build.
    - name: Generates Pages
      run: |
        npm run build

    - name: Deploy Github Pages🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        repository-name: toimc-team/notes-page # The branch the action should deploy to.
        branch: master
        folder: ./src/.vuepress/dist # The folder the action should deploy.
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Sync to Gitee Page
      uses: wearerequired/git-mirror-action@master
      env:
        # 注意在 Settings->Secrets 配置 GITEE_PRIVATE_KEY
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
        # 注意替换为你的 GitHub 源仓库地址
        source-repo: git@github.com:RunWorldZBL/notes-page.git
        # 注意替换为你的 Gitee 目标仓库地址
        destination-repo: git@gitee.com:zblh/notes-page.git

    - name: Trigger Gitee Pages Auto Reload
      uses: yanglbme/gitee-pages-action@master
      with:
        # 注意替换为你的 Gitee 用户名
        gitee-username: 2690420490@qq.com
        # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
        gitee-password: 20011114..
        # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
        gitee-repo: zblh/notes-page
